import './globals.css';
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import PwaInstaller from "./_components/PwaInstaller"; // ✅ ruta correcta

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "#c83b94",
  icons: {
    icon: [
      { url: "/icons/icon-192.png", sizes: "192x192" },
      { url: "/icons/icon-512.png", sizes: "512x512" },
    ],
    apple: "/icons/icon-192.png",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`bg-gray-900 text-white min-h-screen ${geistSans.variable} ${geistMono.variable}`}>
        <PwaInstaller /> {/* registra /sw.js */}
        {children}
      </body>
    </html>
  );
}
